apiVersion: v1
kind: Service
metadata:
  name: cachet-svc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: cachethq
---
# deploy cachethq  with 2 replicas
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cachethq
  labels:
    app: cachethq
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cachethq
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: cachethq
        tier: frontend
    spec:
      containers:
      - image: cachethq/docker:latest
        name: cachethq
        ports:
        - containerPort: 8000
          name: cachethq
        env:
        - name: "DB_DRIVER"
          value: "mysql"
        - name: "DB_DATABASE"
          value: "cachetdb"
        - name: "DB_HOST"
          value: mysql-svc
        - name: "DB_USERNAME"
          value: "cachetuser"
        - name: "DB_PASSWORD"
          value: ".password"
        - name: "APP_KEY"
          value: ""
        - name: "DB_PORT"
          value: "3306"
        - name: "DB_PREFIX"
          value: "chq_"
        - name: "APP_LOG"
          value: "errorlog"
        - name: "DEBUG"
          value: "true"
        - name: "MAIL_HOST"
          value: "smtp.example.com"
        - name: "APP_URL"
          value: "cachet.domain.com"
