apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
spec:
  storageClassName: vault-nfs
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.246.32.38
    path: "/opt/postgres"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nfs-pvc
spec:
  storageClassName: vault-nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
