apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: postgres-nfs
  name: postgres-nfs
spec:
  ports:
  - name: "postgres-port"
    port: 5432
    targetPort: 5432
  selector:
    service: postgres-nfs
    type: ClusterIP 
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: vault
  name: vault
spec:
  ports:
  - name: "vault-service"
    port: 8200
    targetPort: 8200
  selector:
    service: vault
    type: ClusterIP 