kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: defaultsc
  annotations:
    storageclass.beta.kubernetes.io/is-default-class: "true"
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
  zone: us-east-2c
