apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql
  labels:
    app: postgres
data:
  POSTGRES_DB: postgresdb
  POSTGRES_USER: admin
  POSTGRES_PASSWORD: 
  PGDATA: /var/lib/postgresql/data
