apiVersion: "v1"
kind: "PersistentVolume"
metadata:
  name: "eb-aws-pv"
spec:
  capacity:
    storage: "5Gi"
  accessModes:
    - "ReadWriteOnce"
  awsElasticBlockStore:
    fsType: "gp2"
    volumeID: "<ID VOLUME>"
---
kind: "PersistentVolumeClaim"
apiVersion: "v1"
metadata:
  name: "eb-aws-pvclaim"
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "5Gi"
  volumeName: "eb-aws-pv"
