apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-nfs-pv
spec:
  storageClassName: jenkins-nfs
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.246.32.38
    path: "/opt/jenkins"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jenkins-nfs-pvc
spec:
  storageClassName: jenkins-nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
